### ISSUE TITLE
possível vulnerabilidade em adb.exe

### ISSUE THREAD

**Issue by 0x5FE** [AvillaDaniel/AvillaForensics#10]
O adb.exe parece ser executado com argumentos que poderiam ser potencialmente manipulados por um invasor. Mais especificamente manipular a entrada backupPath para executar comandos arbitrários no contexto de backgroundWorker1_DoWork.

Por exemplo: \"; echo 'command' > comand.txt ; \" 

Nesse exemplo, adicionar ponto e vírgula (;) para separar comandos + o código poderia fazer com que o invasor conseguisse executar quaisquer comandos que desejar no sistema.

**Comment by AvillaDaniel** [comment]
Obrigado por avisar, sempre recomendo que os usuários baixem a versão compilada somente pelo link que forneço e que não baixe a ferramenta de terceiros, pois qualquer pode compilar o código e gerar uma versão modificada.
