### ISSUE TITLE
Backup ADB Not Working for Android 13

### ISSUE THREAD

**Issue by RandomGrep** [AvillaDaniel/AvillaForensics#21]
First, I connected my Android device and then tested the connection it was ok, then I selected the destination for the .adb files and then extracted. I got backup screen on my android device and after that my device went to restart and in logs I saw Extraction completed but all the .adb files are empty!
![vL8SnSoRIoad](https://github.com/user-attachments/assets/8fef3451-72f2-4799-b791-45c1b2d33749)

**Comment by AvillaDaniel** [comment]
Hi, you put spaces in the folder name and it should look like this: "Mobile_Foresnics" or "Mobile-Forenics".

It shouldn't look like this: "Mobile Forensics"
